CREATE DATABASE netwatch;
use netwatch;
select * from network_element;
select * from network_site;
select * from network_alarm;
select * from topology_link;
select * from trouble_ticket;
select * from user;
select * from audit_log;
select * from capacity_record;
select * from circuit;
select * from field_dispatch;
select * from maintenance_window;
select * from provisioning_request;